function tool_SE3 = scarafkine(l_vec,th_mat)
% get forward kinematics of scara robot from joint angles
%SCARAFKINE
%    TOOL_T = SCARAFKINE(L1,L2,L3,TH1,TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Aug-2019 18:54:07

l1 = l_vec(1); l2 = l_vec(2); l3 = l_vec(3); l4 = l_vec(4);
for i=1:size(th_mat,1)
    th1 = th_mat(i,1); th2 = th_mat(i,2); th3 = th_mat(i,3); th4 = th_mat(i,4);   
    t2 = sin(th3);
    t3 = cos(th3);
    t4 = th1+th2;
    tool_T = reshape([t3,t2,0.0,0.0,-t2,t3,0.0,0.0,0.0,0.0,1.0,0.0,l2.*cos(t4)+l1.*cos(th1),l2.*sin(t4)+l1.*sin(th1),th4,1.0],[4,4]);
    tool_SE3(i) = SE3(tool_T);
end