function tool_SE3 = fkine4(l_vec,th_mat)
% get forward kinematics of scara robot from joint angles (4 dof)
%SCARAFKINE
%    TOOL_T = SCARAFKINE(L1,L2,L3,TH1,TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    06-Aug-2019 18:54:07

l1 = l_vec(1); l2 = l_vec(2); l3 = l_vec(3); l4 = l_vec(4);
for i=1:size(th_mat,1)
    th1 = th_mat(i,1); th2 = th_mat(i,2); th3 = th_mat(i,3); th4 = th_mat(i,4);   
    x = l1*cos(th1)+l2*cos(th1+th2)+l4*cos(th1+th2+th4);
    y = l1*sin(th1)+l2*sin(th1+th2)+l4*sin(th1+th2+th4);
    z = l3-th3;
    a = th1+th2+th4;
    tool_T = rt2tr(rotz(a),[x,y,z]);
    tool_SE3(i) = SE3(tool_T);
end